// Mocks generated by Mockito 5.4.4 from annotations
// in budget_tracker/test/features/transactions/domain/usecases/add_transaction_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:budget_tracker/core/error/result.dart' as _i4;
import 'package:budget_tracker/features/transactions/domain/entities/transaction.dart'
    as _i5;
import 'package:budget_tracker/features/transactions/domain/entities/transaction_filter.dart'
    as _i7;
import 'package:budget_tracker/features/transactions/domain/repositories/transaction_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i2.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Transaction>>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.Transaction>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.Transaction>>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.Transaction>>>);

  @override
  _i3.Future<_i4.Result<_i5.Transaction?>> getById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.Transaction?>>.value(
            _i6.dummyValue<_i4.Result<_i5.Transaction?>>(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.Transaction?>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Transaction>>> getByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.Transaction>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.Transaction>>>(
          this,
          Invocation.method(
            #getByDateRange,
            [
              start,
              end,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.Transaction>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Transaction>>> getByCategory(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByCategory,
          [categoryId],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.Transaction>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.Transaction>>>(
          this,
          Invocation.method(
            #getByCategory,
            [categoryId],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.Transaction>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Transaction>>> getByType(
          _i5.TransactionType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByType,
          [type],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.Transaction>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.Transaction>>>(
          this,
          Invocation.method(
            #getByType,
            [type],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.Transaction>>>);

  @override
  _i3.Future<_i4.Result<_i5.Transaction>> add(_i5.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [transaction],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.Transaction>>.value(
            _i6.dummyValue<_i4.Result<_i5.Transaction>>(
          this,
          Invocation.method(
            #add,
            [transaction],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.Transaction>>);

  @override
  _i3.Future<_i4.Result<_i5.Transaction>> update(
          _i5.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [transaction],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.Transaction>>.value(
            _i6.dummyValue<_i4.Result<_i5.Transaction>>(
          this,
          Invocation.method(
            #update,
            [transaction],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.Transaction>>);

  @override
  _i3.Future<_i4.Result<void>> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #delete,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<double>> getTotalAmount(
    DateTime? start,
    DateTime? end, {
    _i5.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalAmount,
          [
            start,
            end,
          ],
          {#type: type},
        ),
        returnValue: _i3.Future<_i4.Result<double>>.value(
            _i6.dummyValue<_i4.Result<double>>(
          this,
          Invocation.method(
            #getTotalAmount,
            [
              start,
              end,
            ],
            {#type: type},
          ),
        )),
      ) as _i3.Future<_i4.Result<double>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Transaction>>> search(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.Transaction>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.Transaction>>>(
          this,
          Invocation.method(
            #search,
            [query],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.Transaction>>>);

  @override
  _i3.Future<_i4.Result<int>> getCount() => (super.noSuchMethod(
        Invocation.method(
          #getCount,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Result<int>>.value(_i6.dummyValue<_i4.Result<int>>(
          this,
          Invocation.method(
            #getCount,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Result<int>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Transaction>>> getTransactionsPaginated({
    int? limit = 20,
    int? offset = 0,
    _i7.TransactionFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionsPaginated,
          [],
          {
            #limit: limit,
            #offset: offset,
            #filter: filter,
          },
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.Transaction>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.Transaction>>>(
          this,
          Invocation.method(
            #getTransactionsPaginated,
            [],
            {
              #limit: limit,
              #offset: offset,
              #filter: filter,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.Transaction>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Transaction>>>
      getTransactionsPaginatedByDateRange(
    DateTime? start,
    DateTime? end, {
    int? limit = 20,
    int? offset = 0,
    _i7.TransactionFilter? filter,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getTransactionsPaginatedByDateRange,
              [
                start,
                end,
              ],
              {
                #limit: limit,
                #offset: offset,
                #filter: filter,
              },
            ),
            returnValue: _i3.Future<_i4.Result<List<_i5.Transaction>>>.value(
                _i6.dummyValue<_i4.Result<List<_i5.Transaction>>>(
              this,
              Invocation.method(
                #getTransactionsPaginatedByDateRange,
                [
                  start,
                  end,
                ],
                {
                  #limit: limit,
                  #offset: offset,
                  #filter: filter,
                },
              ),
            )),
          ) as _i3.Future<_i4.Result<List<_i5.Transaction>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Transaction>>> getPaginated({
    int? limit = 20,
    int? offset = 0,
    _i7.TransactionFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaginated,
          [],
          {
            #limit: limit,
            #offset: offset,
            #filter: filter,
          },
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.Transaction>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.Transaction>>>(
          this,
          Invocation.method(
            #getPaginated,
            [],
            {
              #limit: limit,
              #offset: offset,
              #filter: filter,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.Transaction>>>);

  @override
  _i3.Future<_i4.Result<int>> getFilteredCount(_i7.TransactionFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilteredCount,
          [filter],
        ),
        returnValue:
            _i3.Future<_i4.Result<int>>.value(_i6.dummyValue<_i4.Result<int>>(
          this,
          Invocation.method(
            #getFilteredCount,
            [filter],
          ),
        )),
      ) as _i3.Future<_i4.Result<int>>);
}
