// Mocks generated by Mockito 5.4.4 from annotations
// in budget_tracker/test/features/collaboration/domain/usecases/create_shared_budget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:budget_tracker/core/error/result.dart' as _i4;
import 'package:budget_tracker/features/collaboration/domain/entities/shared_budget.dart'
    as _i5;
import 'package:budget_tracker/features/collaboration/domain/repositories/shared_budget_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SharedBudgetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedBudgetRepository extends _i1.Mock
    implements _i2.SharedBudgetRepository {
  MockSharedBudgetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.SharedBudget?>> getSharedBudgetById(
          String? budgetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSharedBudgetById,
          [budgetId],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.SharedBudget?>>.value(
            _i6.dummyValue<_i4.Result<_i5.SharedBudget?>>(
          this,
          Invocation.method(
            #getSharedBudgetById,
            [budgetId],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.SharedBudget?>>);

  @override
  _i3.Future<_i4.Result<List<_i5.SharedBudget>>> getSharedBudgetsForUser(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSharedBudgetsForUser,
          [userId],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.SharedBudget>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.SharedBudget>>>(
          this,
          Invocation.method(
            #getSharedBudgetsForUser,
            [userId],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.SharedBudget>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.SharedBudget>>> getOwnedSharedBudgets(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOwnedSharedBudgets,
          [userId],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.SharedBudget>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.SharedBudget>>>(
          this,
          Invocation.method(
            #getOwnedSharedBudgets,
            [userId],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.SharedBudget>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.SharedBudget>>> getMemberSharedBudgets(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemberSharedBudgets,
          [userId],
        ),
        returnValue: _i3.Future<_i4.Result<List<_i5.SharedBudget>>>.value(
            _i6.dummyValue<_i4.Result<List<_i5.SharedBudget>>>(
          this,
          Invocation.method(
            #getMemberSharedBudgets,
            [userId],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<_i5.SharedBudget>>>);

  @override
  _i3.Future<_i4.Result<_i5.SharedBudget>> createSharedBudget(
          _i5.SharedBudget? budget) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSharedBudget,
          [budget],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.SharedBudget>>.value(
            _i6.dummyValue<_i4.Result<_i5.SharedBudget>>(
          this,
          Invocation.method(
            #createSharedBudget,
            [budget],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.SharedBudget>>);

  @override
  _i3.Future<_i4.Result<_i5.SharedBudget>> updateSharedBudget(
          _i5.SharedBudget? budget) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSharedBudget,
          [budget],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.SharedBudget>>.value(
            _i6.dummyValue<_i4.Result<_i5.SharedBudget>>(
          this,
          Invocation.method(
            #updateSharedBudget,
            [budget],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.SharedBudget>>);

  @override
  _i3.Future<_i4.Result<void>> deleteSharedBudget(String? budgetId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSharedBudget,
          [budgetId],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #deleteSharedBudget,
            [budgetId],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.SharedBudget>> addMember(
    String? budgetId,
    String? userId,
    _i5.BudgetPermission? permission,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMember,
          [
            budgetId,
            userId,
            permission,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.SharedBudget>>.value(
            _i6.dummyValue<_i4.Result<_i5.SharedBudget>>(
          this,
          Invocation.method(
            #addMember,
            [
              budgetId,
              userId,
              permission,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.SharedBudget>>);

  @override
  _i3.Future<_i4.Result<_i5.SharedBudget>> removeMember(
    String? budgetId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [
            budgetId,
            userId,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.SharedBudget>>.value(
            _i6.dummyValue<_i4.Result<_i5.SharedBudget>>(
          this,
          Invocation.method(
            #removeMember,
            [
              budgetId,
              userId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.SharedBudget>>);

  @override
  _i3.Future<_i4.Result<_i5.SharedBudget>> updateMemberPermission(
    String? budgetId,
    String? userId,
    _i5.BudgetPermission? permission,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemberPermission,
          [
            budgetId,
            userId,
            permission,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.SharedBudget>>.value(
            _i6.dummyValue<_i4.Result<_i5.SharedBudget>>(
          this,
          Invocation.method(
            #updateMemberPermission,
            [
              budgetId,
              userId,
              permission,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.SharedBudget>>);

  @override
  _i3.Future<_i4.Result<void>> sendInvitation(
    String? budgetId,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendInvitation,
          [
            budgetId,
            email,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #sendInvitation,
            [
              budgetId,
              email,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.SharedBudget>> acceptInvitation(
    String? budgetId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptInvitation,
          [
            budgetId,
            userId,
          ],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.SharedBudget>>.value(
            _i6.dummyValue<_i4.Result<_i5.SharedBudget>>(
          this,
          Invocation.method(
            #acceptInvitation,
            [
              budgetId,
              userId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.SharedBudget>>);

  @override
  _i3.Future<_i4.Result<void>> declineInvitation(
    String? budgetId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #declineInvitation,
          [
            budgetId,
            userId,
          ],
        ),
        returnValue:
            _i3.Future<_i4.Result<void>>.value(_i6.dummyValue<_i4.Result<void>>(
          this,
          Invocation.method(
            #declineInvitation,
            [
              budgetId,
              userId,
            ],
          ),
        )),
      ) as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<String>>> getPendingInvitations(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingInvitations,
          [userId],
        ),
        returnValue: _i3.Future<_i4.Result<List<String>>>.value(
            _i6.dummyValue<_i4.Result<List<String>>>(
          this,
          Invocation.method(
            #getPendingInvitations,
            [userId],
          ),
        )),
      ) as _i3.Future<_i4.Result<List<String>>>);
}
